/* Generated By:JavaCC: Do not edit this line. FunParserTreeConstants.java Version 5.0 */
package fun.parser;

public interface FunParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTSTATICTEXT = 1;
  public int JJTLITERALTEXT = 2;
  public int JJTSITESTATEMENT = 3;
  public int JJTCORESTATEMENT = 4;
  public int JJTDEFAULTSTATEMENT = 5;
  public int JJTVOID = 6;
  public int JJTEXTERNSTATEMENT = 7;
  public int JJTADOPTSTATEMENT = 8;
  public int JJTKEEPSTATEMENT = 9;
  public int JJTREDIRECTSTATEMENT = 10;
  public int JJTCONTINUESTATEMENT = 11;
  public int JJTSTATICBLOCK = 12;
  public int JJTFUNBLOCK = 13;
  public int JJTCONCURRENTFUNBLOCK = 14;
  public int JJTEXTERNALCOLLECTIONDEFINITION = 15;
  public int JJTEXTERNALDEFINITION = 16;
  public int JJTANONYMOUSDEFINITION = 17;
  public int JJTCOLLECTIONDEFINITION = 18;
  public int JJTCOMPLEXDEFINITION = 19;
  public int JJTELEMENTDEFINITION = 20;
  public int JJTARGUMENTS = 21;
  public int JJTELLIPSIS = 22;
  public int JJTANONYMOUSARRAY = 23;
  public int JJTANONYMOUSTABLE = 24;
  public int JJTTABLEELEMENT = 25;
  public int JJTTYPELIST = 26;
  public int JJTTYPE = 27;
  public int JJTNAME = 28;
  public int JJTDIM = 29;
  public int JJTDEFCOLLECTIONNAME = 30;
  public int JJTDEFTYPENAME = 31;
  public int JJTDEFELEMENTNAME = 32;
  public int JJTPARAMETERLIST = 33;
  public int JJTDEFPARAMETER = 34;
  public int JJTANY = 35;
  public int JJTANYANY = 36;
  public int JJTPRIMITIVETYPE = 37;
  public int JJTCONDITIONALEXPRESSION = 38;
  public int JJTWITHPREDICATE = 39;
  public int JJTWITHOUTPREDICATE = 40;
  public int JJTFOREXPRESSION = 41;
  public int JJTITERATORVALUES = 42;
  public int JJTDYNAMICELEMENTBLOCK = 43;
  public int JJTVALUEEXPRESSION = 44;
  public int JJTCHOICEEXPRESSION = 45;
  public int JJTBINARYEXPRESSION = 46;
  public int JJTUNARYEXPRESSION = 47;
  public int JJTCONSTRUCTION = 48;
  public int JJTBREAKSTATEMENT = 49;
  public int JJTNEXTCONSTRUCTION = 50;
  public int JJTSUBCONSTRUCTION = 51;
  public int JJTSUPERCONSTRUCTION = 52;
  public int JJTCOMPLEXNAME = 53;
  public int JJTSPECIALNAME = 54;
  public int JJTNAMEWITHARGUMENTS = 55;
  public int JJTNAMEWITHINDEXES = 56;
  public int JJTINDEX = 57;
  public int JJTLOGICALOROPERATOR = 58;
  public int JJTLOGICALANDOPERATOR = 59;
  public int JJTEQUALSOPERATOR = 60;
  public int JJTNOTEQUALSOPERATOR = 61;
  public int JJTLESSTHANOPERATOR = 62;
  public int JJTGREATERTHANOPERATOR = 63;
  public int JJTLESSTHANOREQUALOPERATOR = 64;
  public int JJTGREATERTHANOREQUALOPERATOR = 65;
  public int JJTINOPERATOR = 66;
  public int JJTLEFTSHIFTOPERATOR = 67;
  public int JJTRIGHTSHIFTOPERATOR = 68;
  public int JJTRIGHTUNSIGNEDSHIFTOPERATOR = 69;
  public int JJTADDOPERATOR = 70;
  public int JJTSUBTRACTOPERATOR = 71;
  public int JJTMULTIPLYOPERATOR = 72;
  public int JJTDIVIDEBYOPERATOR = 73;
  public int JJTMODOPERATOR = 74;
  public int JJTOROPERATOR = 75;
  public int JJTXOROPERATOR = 76;
  public int JJTANDOPERATOR = 77;
  public int JJTNEGATEOPERATOR = 78;
  public int JJTBITFLIPOPERATOR = 79;
  public int JJTLOGICALNOTOPERATOR = 80;
  public int JJTTYPEOPERATOR = 81;
  public int JJTISAEXPRESSION = 82;
  public int JJTINTEGERLITERAL = 83;
  public int JJTFLOATINGPOINTLITERAL = 84;
  public int JJTCHARLITERAL = 85;
  public int JJTSTRINGLITERAL = 86;
  public int JJTBOOLEANLITERAL = 87;
  public int JJTNULLLITERAL = 88;


  public String[] jjtNodeName = {
    "Root",
    "StaticText",
    "LiteralText",
    "SiteStatement",
    "CoreStatement",
    "DefaultStatement",
    "void",
    "ExternStatement",
    "AdoptStatement",
    "KeepStatement",
    "RedirectStatement",
    "ContinueStatement",
    "StaticBlock",
    "FunBlock",
    "ConcurrentFunBlock",
    "ExternalCollectionDefinition",
    "ExternalDefinition",
    "AnonymousDefinition",
    "CollectionDefinition",
    "ComplexDefinition",
    "ElementDefinition",
    "Arguments",
    "Ellipsis",
    "AnonymousArray",
    "AnonymousTable",
    "TableElement",
    "TypeList",
    "Type",
    "Name",
    "Dim",
    "DefCollectionName",
    "DefTypeName",
    "DefElementName",
    "ParameterList",
    "DefParameter",
    "Any",
    "AnyAny",
    "PrimitiveType",
    "ConditionalExpression",
    "WithPredicate",
    "WithoutPredicate",
    "ForExpression",
    "IteratorValues",
    "DynamicElementBlock",
    "ValueExpression",
    "ChoiceExpression",
    "BinaryExpression",
    "UnaryExpression",
    "Construction",
    "BreakStatement",
    "NextConstruction",
    "SubConstruction",
    "SuperConstruction",
    "ComplexName",
    "SpecialName",
    "NameWithArguments",
    "NameWithIndexes",
    "Index",
    "LogicalOrOperator",
    "LogicalAndOperator",
    "EqualsOperator",
    "NotEqualsOperator",
    "LessThanOperator",
    "GreaterThanOperator",
    "LessThanOrEqualOperator",
    "GreaterThanOrEqualOperator",
    "InOperator",
    "LeftShiftOperator",
    "RightShiftOperator",
    "RightUnsignedShiftOperator",
    "AddOperator",
    "SubtractOperator",
    "MultiplyOperator",
    "DivideByOperator",
    "ModOperator",
    "OrOperator",
    "XorOperator",
    "AndOperator",
    "NegateOperator",
    "BitflipOperator",
    "LogicalNotOperator",
    "TypeOperator",
    "IsaExpression",
    "IntegerLiteral",
    "FloatingPointLiteral",
    "CharLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
  };
}
/* JavaCC - OriginalChecksum=f5bc0e09a17a10d8f26823699ce53d1e (do not edit this line) */
