/* Fun Compiler and Runtime Engine
 * ParsedTypeList.java
 *
 * Copyright (c) 2017 by Fun Development
 * All rights reserved.
 */

package fun.parser;

import fun.lang.*;

import java.util.*;


/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.3 $
 */
public class ParsedTypeList extends TypeList implements Initializable {
    public ParsedTypeList(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        ArrayList list = new ArrayList(Arrays.asList(children));
        setList(list);
    }
}
