/* Fun Compiler and Runtime Engine
 * ParsedSiteStatement.java
 *
 * Copyright (c) 2017 by Fun Development
 * All rights reserved.
 */

package fun.parser;

import fun.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */

public class ParsedSiteStatement extends Site implements Initializable {
    public ParsedSiteStatement(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int n = 0;
        if (children.length > 2) {
            setDomainName(children[0].getName());
            n = 1;
        }
        setName((NameNode) children[n]);
        setType(createType());
        setContents(children[n+1]);
    }
}

