/* Fun
 *
 * $Id: ParsedArguments.java,v 1.9 2014/11/01 19:49:40 sthippo Exp $
 *
 * Copyright (c) 2002-2015 by fundev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Fun Poetic License at http://www.fundev.org/poetic-license.html
 */

package fun.parser;

import fun.lang.*;


/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.9 $
 */
public class ParsedArguments extends ArgumentList implements Initializable {
    public ParsedArguments(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        init(children);
    }
    
    public void setDynamic() {
        setDynamic(true);
    }

    public void setConcurrent() {
        setConcurrent(true);
    }
    
    public void setArray() {
        setArray(true);
    }
    
    public void setTable() {
        setTable(true);
    }
}
