/* Fun
 *
 * $Id: ParsedNextConstruction.java,v 1.5 2013/04/10 03:29:30 sthippo Exp $
 *
 * Copyright (c) 2002-2013 by fundev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Fun Poetic License at http://www.fundev.org/poetic-license.html
 */

package fun.parser;

import fun.lang.NextStatement;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */

public class ParsedNextConstruction extends NextStatement {
    public ParsedNextConstruction(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
