/* Fun Compiler and Runtime Engine
 * ParsedNode.java
 *
 * Copyright (c) 2017 by Fun Development
 * All rights reserved.
 */

package fun.parser;

import fun.lang.*;

/**
 * A convenience concrete subclass of AbstractNode which can serve as the base
 * class of the objects generated by the parser which are not subclasses of concrete for fun nodes.  Nodes are either primitive
 * classes in fun.lang.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.3 $
 */
public class ParsedNode extends AbstractNode {

    public ParsedNode() {
        super();
    }

    public boolean isPrimitive() {
        return false;
    }

    public boolean isStatic() {
        return false;
    }

    public boolean isDynamic() {
        return false;
    }

    public boolean isDefinition() {
        return false;
    }
}
