/* Fun
 *
 * $Id: ParsedDefElementName.java,v 1.4 2014/11/01 19:49:41 sthippo Exp $
 *
 * Copyright (c) 2002-2014 by fundev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Fun Poetic License at http://www.fundev.org/poetic-license.html
 */

package fun.parser;

import fun.lang.*;

import java.util.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.4 $
 */
public class ParsedDefElementName extends NameWithDims implements Initializable {
    public ParsedDefElementName(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int len = children.length;
        List<Dim> dims;
        if (len == 0) {
            dims = new EmptyList<Dim>();

        } else if (len == 1) {
            dims = new SingleItemList<Dim>((Dim) children[0]);

        } else {
            dims = Arrays.asList((Dim[]) children);
        }
        setDims(dims);
    }
}
