/* Generated By:JJTree: Do not edit this line. ParsedArrayIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Parsed,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package fun.parser;

public
class ParsedArrayIndex extends SimpleNode {
  public ParsedArrayIndex(int id) {
    super(id);
  }

  public ParsedArrayIndex(FunParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FunParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ed1bc3b89b395686d1e8d3e8020688a (do not edit this line) */
