/* Fun Compiler and Runtime Engine
 * ParsedPrimitiveType.java
 *
 * Copyright (c) 2017 by Fun Development
 * All rights reserved.
 */

package fun.parser;

import fun.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.6 $
 */
public class ParsedPrimitiveType extends PrimitiveType {
    public ParsedPrimitiveType(int id) {
        super();
    }

    void makeBoolean() {
        setType(Boolean.TYPE);
    }
    void makeChar() {
        setType(Character.TYPE);
    }
    void makeByte() {
        setType(Byte.TYPE);
    }
    void makeShort() {
        setType(Short.TYPE);
    }
    void makeInt() {
        setType(Integer.TYPE);
    }
    void makeLong() {
        setType(Long.TYPE);
    }
    void makeFloat() {
        setType(Float.TYPE);
    }
    void makeDouble() {
        setType(Double.TYPE);
    }
    void makeNumber() {
        setType(Number.class);
    }
    void makeString() {
        setType(String.class);
    }
    void makeContinuation() {
        setType(Continuation.class);
    }
    void makeVoid() {
        setType(Void.TYPE);
    }
    

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
