/* Fun
 *
 * $Id: ParsedSpecialName.java,v 1.5 2007/09/25 22:36:56 sthippo Exp $
 *
 * Copyright (c) 2003-2015 by fundev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Fun Poetic License at http://www.fundev.org/poetic-license.html
 */

package fun.parser;

import fun.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */

public class ParsedSpecialName extends NameNode {
    public ParsedSpecialName(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    public boolean isSpecial() {
    	return true;
    }
}
