/* Generated By:JJTree: Do not edit this line. ParsedTableIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Parsed,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package fun.parser;

public
class ParsedTableIndex extends SimpleNode {
  public ParsedTableIndex(int id) {
    super(id);
  }

  public ParsedTableIndex(FunParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FunParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dde61d58cb4a84d9eaf71d61ad804811 (do not edit this line) */
