/* Fun
 *
 * $Id: ParsedNode.java,v 1.3 2005/06/30 04:20:55 sthippo Exp $
 *
 * Copyright (c) 2002-2005 by fundev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Fun Poetic License at http://www.fundev.org/poetic-license.html
 */

package fun.parser;

import fun.lang.*;

/**
 * A convenience concrete subclass of AbstractNode which can serve as the base
 * class of the objects generated by the parser which are not subclasses of concrete for fun nodes.  Nodes are either primitive
 * classes in fun.lang.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.3 $
 */
public class ParsedNode extends AbstractNode {

    public ParsedNode() {
        super();
    }

    public boolean isPrimitive() {
        return false;
    }

    public boolean isStatic() {
        return false;
    }

    public boolean isDynamic() {
        return false;
    }

    public boolean isDefinition() {
        return false;
    }
}
