/* Fun Compiler and Runtime Engine
 * ParsedBooleanLiteral.java
 *
 * Copyright (c) 2017 by Fun Development
 * All rights reserved.
 */

package fun.parser;

import fun.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.3 $
 */

public class ParsedBooleanLiteral extends PrimitiveValue {
    public ParsedBooleanLiteral(int id) {
        super(false);
    }

    public void setValue(boolean value) {
        setValueAndClass(new Boolean(value), Boolean.TYPE);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
