/* Fun Compiler and Runtime Engine
 * ParsedNullLiteral.java
 *
 * Copyright (c) 2017 by Fun Development
 * All rights reserved.
 */

package fun.parser;

import fun.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.3 $
 */
public class ParsedNullLiteral extends NullValue {
    public ParsedNullLiteral(int id) {
        super();
    }

    public void setPrimitive() {
        setType(PRIMITIVE);
    }

    public void setStatic() {
        setType(STATIC_BLOCK);
    }

    public void setDynamic() {
        setType(DYNAMIC_BLOCK);
    }

    public void setAbstract() {
        setType(ABSTRACT_BLOCK);
    }

    public void setExternal() {
        setType(EXTERNAL_BLOCK);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(FunParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
